### ISSUE TITLE
rails 3 -- undefined method 'gravatar_image_tag'

### ISSUE THREAD

**Issue by jamessross** [mdeering/gravatar_image_tag#4]
I am getting this error after I installed the gem:

ActionView::Template::Error (undefined method `gravatar_image_tag' for #<#Class:0x1940c580x193ef18):
    1: <h1>
    2:   <%= gravatar_image_tag @user.email %>
    3:   <%= @user.name %>
    4: </h1>
    5:

 app/views/users/show.html.erb:2:in '_app_views_users_show_html_erb__623389499_13233936__799847888'

I am using version 1.0.0.pre2, although I had the same error with 0.1.0.
I am Windows XP SP3, if that matters.  Is this a routing issue? 
Sorry, I am quite new to this and am running through a tutorial that uses this gem.

any help would be appreciated.

**Comment by markotuya0** [comment]
> I had to restart the server to get it to work. Consider this issue closed.

thanks worked for me
